name: Build & upload to Firebase App Distribution

on:
  push

jobs:
  build:
    name: Building and Distributing app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Create Google Services JSON File
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_CONTENT }}
        run: echo $GOOGLE_SERVICES_CONTENT | base64 -di > app/google-services.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release
        run: ./gradlew assembleInternalDebug

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT }}
          groups: Owner
          file: app/build/outputs/apk/internal/debug/Rivo-internalDebug-code1-v2024.02.00.apk